"""Tests for the ``creative-generate`` skill (Creative Studio PR-C).

The skill is the flagship deliverable of Creative Studio: it encodes the
quality-first 6-step workflow (brief → copy → visuals → art-direction
loop → compose → deliver) over the ``creative_studio_*`` MCP tools.

These tests pin two things a future edit could silently break:

1. The SKILL.md stays **loadable** — it parses cleanly through the real
   ``mureo.core.skills.parser.parse_skill_md`` used by discovery.
2. The load-bearing workflow rules are present (the 5 tools, the
   art-direction pass bar, the never-score-unseen iron rule, the
   negative-space-per-template guidance, the host-without-file-access
   convention, and the creative-refresh cross-link).

Both the packaged copy (``mureo/_data/skills``) and the repo-root mirror
(``skills/``) are checked and must stay byte-identical.
"""

from __future__ import annotations

from pathlib import Path

import pytest

from mureo.core.skills.parser import parse_skill_md

REPO_ROOT = Path(__file__).resolve().parent.parent
_PACKAGED = REPO_ROOT / "mureo" / "_data" / "skills" / "creative-generate" / "SKILL.md"
_MIRROR = REPO_ROOT / "skills" / "creative-generate" / "SKILL.md"
_SKILL_PATHS = (_PACKAGED, _MIRROR)


def _read(path: Path) -> str:
    return path.read_text(encoding="utf-8")


@pytest.mark.unit
class TestCreativeGenerateSkillLoadable:
    @pytest.mark.parametrize("path", _SKILL_PATHS)
    def test_skill_file_exists(self, path: Path) -> None:
        assert path.exists(), f"missing skill file: {path}"

    @pytest.mark.parametrize("path", _SKILL_PATHS)
    def test_frontmatter_parses(self, path: Path) -> None:
        """The SKILL.md must load through the real parser used by
        discovery — a malformed frontmatter would drop the skill."""
        entry = parse_skill_md(path)
        assert entry.name == "creative-generate"
        assert entry.description
        # Trigger phrases the operator will actually type.
        assert "banner" in entry.description.lower()
        assert "クリエイティブ作成" in entry.description
        # metadata block is preserved verbatim in extra (forward-compat).
        assert "metadata" in entry.extra
        assert entry.extra["metadata"]["version"] == "0.10.20"

    def test_copies_are_byte_identical(self) -> None:
        """The packaged copy and the repo-root mirror must not drift."""
        assert _read(_PACKAGED) == _read(_MIRROR)


@pytest.mark.unit
class TestCreativeGenerateWorkflow:
    @pytest.mark.parametrize("path", _SKILL_PATHS)
    def test_references_all_five_tools(self, path: Path) -> None:
        body = _read(path)
        for tool in (
            "creative_studio_providers_list",
            "creative_studio_generate_visual",
            "creative_studio_compose",
            "creative_studio_edit_visual",
            "creative_studio_brand_kit_get",
        ):
            assert tool in body, f"skill must reference {tool}"

    @pytest.mark.parametrize("path", _SKILL_PATHS)
    def test_art_direction_pass_bar_pinned(self, path: Path) -> None:
        """The scoring bar is the heart of the quality loop — pin the
        exact thresholds so an edit cannot silently loosen them."""
        body = _read(path)
        assert "28/35" in body
        assert "3 edit rounds" in body

    @pytest.mark.parametrize("path", _SKILL_PATHS)
    def test_never_score_unseen_iron_rule(self, path: Path) -> None:
        """Scoring an image you did not actually Read is the cardinal
        failure mode — the rule must be stated explicitly."""
        lower = _read(path).lower()
        assert "never score an image you have not actually seen" in lower

    @pytest.mark.parametrize("path", _SKILL_PATHS)
    def test_copy_never_enters_image_prompt(self, path: Path) -> None:
        """The whole 3-layer premise: text is composed later, never
        generated by the image model."""
        body = _read(path)
        assert "creative-refresh" in body  # rubric cross-reference
        # Normalise whitespace so line-wrapping in the prose does not
        # break the phrase match.
        normalised = " ".join(body.lower().split())
        assert "never put copy text into the image-generation prompt" in normalised

    @pytest.mark.parametrize("path", _SKILL_PATHS)
    def test_negative_space_guidance_per_template(self, path: Path) -> None:
        """Each shipped template has a distinct copy zone; the skill must
        tell the agent how to leave negative space for each."""
        body = _read(path)
        for template in ("hero_overlay", "split", "minimal_badge"):
            assert template in body
        assert "lower third" in body
        assert "center-weighted" in body

    @pytest.mark.parametrize("path", _SKILL_PATHS)
    def test_hosts_without_file_access_section(self, path: Path) -> None:
        """Desktop / Cowork cannot Read PNGs — the skill must tell the
        agent to present paths and NOT invent scores there."""
        body = _read(path)
        assert "Hosts without file access" in body
        assert "Desktop" in body and "Cowork" in body

    @pytest.mark.parametrize("path", _SKILL_PATHS)
    def test_delivery_hands_off_to_existing_upload_tools(self, path: Path) -> None:
        body = _read(path)
        assert "meta_ads_images_upload_file" in body
        assert "google_ads_assets_upload_image" in body
        # Meta dev-mode publishing caveat.
        assert "1885183" in body

    @pytest.mark.parametrize("path", _SKILL_PATHS)
    def test_compose_extra_and_guardrails_documented(self, path: Path) -> None:
        body = _read(path)
        assert "mureo[creative]" in body
        # Guardrails hook: blocked_operations can name the generate tool.
        assert "blocked_operations" in body


@pytest.mark.unit
class TestCreativeRefreshCrossLink:
    """The creative-refresh visual-evaluation section must point new
    creative work at creative-generate (both copies)."""

    _REFRESH_PATHS = (
        REPO_ROOT / "mureo" / "_data" / "skills" / "creative-refresh" / "SKILL.md",
        REPO_ROOT / "skills" / "creative-refresh" / "SKILL.md",
    )

    @pytest.mark.parametrize("path", _REFRESH_PATHS)
    def test_creative_refresh_links_to_generate(self, path: Path) -> None:
        body = _read(path)
        assert "creative-generate" in body
