"""Creative Studio — creator-grade ad-creative (image) generation for mureo.

This package produces the *visual* half of an ad creative: photographic /
illustrative key visuals generated by a pluggable image-generation
provider (OpenAI gpt-image, Google Gemini image, fal.ai FLUX, or any
plugin registered under the ``mureo.image_providers`` entry-point group).

The design deliberately splits the pipeline into layers so each is handled
by the tool best suited to it:

- **Visual layer (this package, PR-A).** Image models generate backgrounds
  and key visuals ONLY, under a hard "no text / no typography" constraint —
  models excel at imagery but butcher rendered (especially Japanese) text.
  :mod:`mureo.creative_studio.providers` abstracts the provider API,
  :mod:`mureo.creative_studio.formats` defines the target format matrix, and
  :mod:`mureo.creative_studio.workspace` owns the on-disk run lifecycle
  (``./creative_studio/<run-id>/`` + a provenance ``manifest.json``).

- **Typography & layout layer (``composer.py``, PR-B).** Headlines, body
  copy, CTAs, logos and badges are composited via HTML/CSS templates
  rendered by headless Chromium so text is pixel-perfect. This arrives in a
  later slice; it is intentionally absent here.

PR-A ships the visual layer plus its MCP tools
(``creative_studio_providers_list`` / ``creative_studio_generate_visual``).
"""

from __future__ import annotations

__all__: list[str] = []
